# Generated by Django 5.1.4 on 2025-01-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='code'),
            preserve_default=False,
        ),
    ]
